<?php

namespace AppBundle\Repository;

/**
 * BlogPostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostsRepository extends \Doctrine\ORM\EntityRepository
{
}
